server {
    listen       80;
    server_name  localhost;

    root  /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location = /config.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0, s-maxage=0";
        add_header CDN-Cache-Control "no-store";
        add_header Surrogate-Control "no-store";
        add_header Pragma "no-cache";
        add_header Expires "0";
        try_files $uri =404;
    }

    location = /tempDashboard {
        return 301 /tempDashboard/;
    }

    location /tempDashboard/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ =404;
    }

    location = /tempDashboard/config.js {
        alias /usr/share/nginx/html/config.js;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0, s-maxage=0";
        add_header CDN-Cache-Control "no-store";
        add_header Surrogate-Control "no-store";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
